apiVersion: apps/v1
kind: Deployment
metadata:
  name: school
spec:
  selector:
    matchLabels:
      app: school
  template:
    metadata:
      labels:
        app: school
    spec:
      containers:
        - name: school
          image: devlangesh/school
          env:
            - name: PORT
              value: "8000"
            - name: MONGO_URI
              value: "mongodb://$(MONGO_SERVICE_HOST):27017"
              # value: mongodb://10.100.231.153:27017
              # value: mongodb+srv://langesh:langesh@cluster0.vsn1uqo.mongodb.net/?retryWrites=true&w=majority
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
