# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mypv
# spec:
#   capacity:
#     storage: 5Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   # persistentVolumeReclaimPolicy: Recycle
#   storageClassName: efs-sc

#   csi:
#     driver: efs.csi.aws.com
#     volumeHandle: fs-0b86aa91ee4458bde

#   # nfs:
#   #   path: /tmp
#   #   server: 172.17.0.2

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "efs-sc"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b86aa91ee4458bde
