apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: "efs-sc"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
